replicaCount: 2
namespace: "kubeapp"
metadata:
 name: ai-svc 
 label: ai-svc

watsonconv:
  apikey: "8tLSMIYpac8MyNu0SWGw6NZaavQ9EUdNydXAD4_XHkW9"
  assistantid: "cca28742-cfcb-47d3-acce-0992c8185d44"
readinessProbe:
  path: /healthz
  port: 3011
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 300

livenessProbe:
  path: /healthz
  port: 3011
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 300
image:
  name: ai-svc
  imageName: "ai-svc" 
  imagePullPolicy: Always
  ports:
    containerPort: 3011
  requests:
    cpu: "50m"
    memory: "300Mi"
  limits:
    cpu: "100m"
    memory: "400Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
      
hpa:
  metadata:
    name: ai-svcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
  scaleTargetRef:  
    name: ai-svc

envOfConfigmaps:
  envASSISTANTID:
    name: ASSISTANTID
    configMapKeyRef:
      name: aimicroservice
      key: ASSISTANTID
  envAPIKEY:
    name: APIKEY
    configMapKeyRef:
      name: aimicroservice
      key: APIKEY

service:
  serviceMetadata:
    name: ai-svc
    labels:
      app: ai-svc
  selector:
    selectorName: ai-svc
  servicePortConfiguration:
    protocol: TCP
    name: ai-svc
    type: ClusterIP
    port: 3011
    targetPort: 3011


imagestream:
  name:  ai-svc
  label: ai-svc

buildconfig:
  uri: "https://github.com/cumulus-bank/ai-microservice.git"
  branch: "master"
  name: "ai-svc"
  imagename: "ai-svc:latest"
  secret1: "secret567"
  secret2: "secret567"

routes:
  host: "ai-svc-kubeapp.apps.9.30.210.207.nip.io"
  targetPort: 3011
  name: ai-svc
  weight: 100


nameOverride: ""
fullnameOverride: ""