replicaCount: 1
namespace: "cumulusbank"
metadata:
 name: aisvc 
 label: aisvc

readinessProbe:
  path: /healthz
  port: 3011
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 300

livenessProbe:
  path: /healthz
  port: 3011
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 300
image:
  name: aisvc
  imageName: "s4saif/cumulus-ai-microservice:latest" 
  imagePullPolicy: Always
  ports:
    containerPort: 3011
  requests:
    cpu: "50m"
    memory: "300Mi"
  limits:
    cpu: "100m"
    memory: "400Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
      
hpa:
  metadata:
    name: aisvcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
  scaleTargetRef:  
    name: aisvc

envOfConfigmaps:
  envASSISTANTID:
    name: ASSISTANTID
    configMapKeyRef:
      name: aimicroservice
      key: ASSISTANTID
  envAPIKEY:
    name: APIKEY
    configMapKeyRef:
      name: aimicroservice
      key: APIKEY

service:
  serviceMetadata:
    name: aisvc
    labels:
      app: aisvc
  selector:
    selectorName: aisvc
  servicePortConfiguration:
    protocol: TCP
    name: aisvc
    type: ClusterIP
    port: 3011
    targetPort: 3011
