
apiVersion: v1
kind: ConfigMap
metadata:
  name: aimicroservice
  namespace: kubeapp
  labels:
    app: {{ .Values.metadata.name }} 
data:
  APIKEY: '8tLSMIYpac8MyNu0SWGw6NZaavQ9EUdNydXAD4_XHkW9'
  ASSISTANTID: 'cca28742-cfcb-47d3-acce-0992c8185d44'