kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cumulusbankaisvc
subjects:
- kind: ServiceAccount
  name: cumulusbankaisvc
roleRef:
  kind: Role
  name: cumulusbankaisvc
  apiGroup: rbac.authorization.k8s.io
